### ISSUE TITLE
Add reporting

### ISSUE THREAD

**Issue by skttl** [Matthew-Wise/Umbraco-CSP-manager#26]
What an awesome package this could be.

Have you thought about adding reporting to it, to make it easier for editors to add or block sources?

Then you could install the package, disallow everything, but set it to reporting only, and have browsers send reports to a local endpoint, which could collect analytics about your site, and present you with an overview of which sources you need to allow/block?

**Comment by Matthew-Wise** [comment]
Thanks, and yes it's something I have considered doing I just need some time to think about the UI. A college has a Optimzely version.

Although he did include a bit of JS to speed up reporting as the browser does it whenever.

Also think long term the static list of directives (script-src) is going to have to become manageable

**Comment by Matthew-Wise** [comment]
Hey @skttl 
Wondered if you have time to help me on this one? 

I am trying to workout the best way of storing the following 

policy broken (script-src)
Blocked Uri (xxxx.js)
The page it was blocked on
How many times this has happened
when it last happened 
If it was back office or front end CSP (I have the code to work this out)

I think there would need to be a composite key of policy and blocked Uri, then maybe a related pages table with the rest?

I have tagged this issue with the branch am working on it in case you wanted to look at it from a code point of view :) entry point for reporting is the CspReportingController
