### ISSUE TITLE
Only one rule can be added at a time, before a refresh is required

### ISSUE THREAD

**Issue by TFAstudio** [Matthew-Wise/Umbraco-CSP-manager#27]
Although the interface seemingly lets you add rule after rule, only the first change is saved. To overcome this issue I refresh the browser or click between Back Office and Front End nodes to refresh the interface, before making another rule. Otherwise my entries and edits are lost.

Using CSP Manager on Umbraco v10.4.2 and v10.5.1.

Ps. Thanks for the neat package. It's mostly excellent!

**Comment by Matthew-Wise** [comment]
Thanks hopefully we can keep improving it, I recently noticed this issue as well. 

I have a fix it in the reporting feature branch so this will be part of the next release

**Comment by Matthew-Wise** [comment]
This release has gone out now :)
