### ISSUE TITLE
Unable to install in Umbraco 13.4.1

### ISSUE THREAD

**Issue by klkkeio** [Matthew-Wise/Umbraco-CSP-manager#42]
The nuget version detecting is greater than13.4.1 to less than or equal to 14.0.

error: NU1103: Unable to find a stable package Umbraco.Cms.Web.BackOffice with version (> 13.4.1 && <= 14.0.0)
error:   - Found 138 version(s) in nuget.org [ Nearest version: 13.4.1 ]

**Comment by Matthew-Wise** [comment]
Hi @klkkeio 

Oops looks like I have my brackets the wrong way round this is now fixed, in 1.4.1

https://www.nuget.org/packages/Umbraco.Community.CSPManager/1.4.1

thanks for letting me know!

Matt
