### ISSUE TITLE
Replace toggles with drop down list

### ISSUE THREAD

**Issue by Rockerby** [Matthew-Wise/Umbraco-CSP-manager#45]
This is super opinionated, but I personally find the toggles very confusing. Perhaps replacing them with a drop down list to make it clearer?

![image](https://github.com/user-attachments/assets/2f98d572-ddb7-4959-855b-bece942ea0c6)

So; CSP Disabled / CSP Enabled for the first
And; Enforced / Report Only for the second

What do you think?

**Comment by Matthew-Wise** [comment]
I have confused myself more than once with them

**Comment by Matthew-Wise** [comment]
Thanks for raise and fixing!!
