### ISSUE TITLE
Show directives in title bar

### ISSUE THREAD

**Issue by Rockerby** [Matthew-Wise/Umbraco-CSP-manager#46]
I think it would be nice to show the directives in the header bar so they can be seen at a glance (I like to organise my CSP by directive, rather than source so this would be helpful).

Something like:

![image](https://github.com/user-attachments/assets/68661ac3-bf00-495e-afa3-f55ab7ff440d)

**Comment by Matthew-Wise** [comment]
Love this idea :)

**Comment by Matthew-Wise** [comment]
Thanks for raise and fixing!!
